/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 26-сен-2024 22:52:42 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS games_grid CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS config CASCADE
;

DROP TABLE IF EXISTS game_config_params CASCADE
;

DROP TABLE IF EXISTS game_log CASCADE
;

DROP TABLE IF EXISTS games CASCADE
;

DROP TABLE IF EXISTS parameters_list CASCADE
;

DROP TABLE IF EXISTS players CASCADE
;

DROP TABLE IF EXISTS users CASCADE
;

/* Create Tables */

CREATE TABLE config
(
	id uuid NOT NULL,
	name varchar(50) NOT NULL,	-- Имя конфигурации
	predefined boolean NOT NULL,
	ord integer NULL
)
;

CREATE TABLE game_config_params
(
	config_id uuid NOT NULL,
	name varchar(50) NOT NULL,	-- Имя параметра
	value varchar(100) NOT NULL	-- Его значение
)
;

CREATE TABLE game_log
(
	game_id uuid NOT NULL,
	tstmp timestamp with time zone NOT NULL,
	command varchar(500) NOT NULL
)
;

CREATE TABLE games
(
	id uuid NOT NULL,
	create_tstmp timestamp with time zone NOT NULL,
	start_tstmp timestamp with time zone NULL,
	end_tstmp timestamp with time zone NULL,
	status varchar(50) NOT NULL,	-- WAITING PLAYING FINISHED
	config_id uuid NOT NULL
)
;

CREATE TABLE parameters_list
(
	name varchar(50) NOT NULL,
	descr varchar(256) NOT NULL,
	type varchar(50) NOT NULL
)
;

CREATE TABLE players
(
	game_id uuid NOT NULL,
	player_name varchar(50) NOT NULL,
	field varchar(2048) NOT NULL,	-- Заполненное поле
	winner boolean NULL
)
;

CREATE TABLE users
(
	name varchar(50) NOT NULL,
	password varchar(150) NOT NULL,
	role varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE config ADD CONSTRAINT pk_config
	PRIMARY KEY (id)
;

CREATE INDEX i_config_games ON config (id ASC)
;

ALTER TABLE game_config_params ADD CONSTRAINT pk_game_config_params
	PRIMARY KEY (config_id,name)
;

CREATE INDEX i_game_config_params_config ON game_config_params (config_id ASC)
;

CREATE INDEX i_game_config_params_parameters_list ON game_config_params (name ASC)
;

ALTER TABLE game_log ADD CONSTRAINT pk_game_log
	PRIMARY KEY (tstmp,game_id)
;

CREATE INDEX i_game_log_game ON game_log (game_id ASC)
;

ALTER TABLE games ADD CONSTRAINT pk_game
	PRIMARY KEY (id)
;

CREATE INDEX i_games_config ON games (config_id ASC)
;

ALTER TABLE parameters_list ADD CONSTRAINT pk_parameters_list
	PRIMARY KEY (name)
;

ALTER TABLE players ADD CONSTRAINT pk_players
	PRIMARY KEY (player_name,game_id)
;

CREATE INDEX i_players ON players (player_name ASC)
;

CREATE INDEX i_players_games ON players (game_id ASC)
;

CREATE INDEX i_games_winners ON players (player_name ASC)
;

ALTER TABLE users ADD CONSTRAINT "PK_Players"
	PRIMARY KEY (name)
;

/* Create Foreign Key Constraints */

ALTER TABLE game_config_params ADD CONSTRAINT fk_game_config_params_config
	FOREIGN KEY (config_id) REFERENCES config (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE game_config_params ADD CONSTRAINT fk_game_config_params_parameters_list
	FOREIGN KEY (name) REFERENCES parameters_list (name) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE game_log ADD CONSTRAINT fk_game_log_game
	FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE games ADD CONSTRAINT fk_games_config
	FOREIGN KEY (config_id) REFERENCES config (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE players ADD CONSTRAINT fk_players_games
	FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE config
	IS 'Сохранённая конфигрурация игры'
;

COMMENT ON COLUMN config.name
	IS 'Имя конфигурации'
;

COMMENT ON TABLE game_config_params
	IS 'Список параметров сохранённой игры'
;

COMMENT ON COLUMN game_config_params.name
	IS 'Имя параметра'
;

COMMENT ON COLUMN game_config_params.value
	IS 'Его значение'
;

COMMENT ON TABLE game_log
	IS 'Статистика игры'
;

COMMENT ON TABLE games
	IS 'Игра'
;

COMMENT ON COLUMN games.status
	IS 'WAITING
PLAYING
FINISHED'
;

COMMENT ON TABLE players
	IS 'Конкретный игрок в конкретной игре'
;

COMMENT ON COLUMN players.field
	IS 'Заполненное поле'
;

/* Create Views */

CREATE OR REPLACE VIEW GAMES_GRID AS
select g.id,
       g.create_tstmp,
       g.status,
       (select string_agg(p.player_name, ' vs ')
        from players p
        where p.game_id = g.id) as players,
    c.name as config_name,
       (select string_agg(p.name || '-' || cp.value, ',')
        from game_config_params cp,
             parameters_list p
        where c.id = g.config_id
          and cp.config_id = c.id
          and p.name = cp.name) as config,
       (CASE
            WHEN g.status = 'FINISHED'
                THEN (select p.player_name from players p where p.game_id = g.id and p.winner = true)
           END)                     as winner
from games g, config c
where g.config_id = c.id and g.status != 'FAILED'
;

COMMENT ON VIEW games_grid
	IS 'Список игр для вывода пользаку'
;
